"""empty message

Revision ID: 06971cf76269
Revises: 617ca9739b3a
Create Date: 2024-01-26 11:32:09.562461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06971cf76269'
down_revision = '617ca9739b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('ltp', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('no_of_trades', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_data')
    # ### end Alembic commands ###
