"""empty message

Revision ID: 617ca9739b3a
Revises: 7759fa999e3d
Create Date: 2024-01-26 01:27:27.694917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617ca9739b3a'
down_revision = '7759fa999e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
